Resources:
  UserProfile:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: userName
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: userName
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: uniqueIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: "ALL"
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.UserTableName}
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
