Resources:
  UserProfile:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: userName
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: userName
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.UserTableName}
